services:
    netgen_layouts.tags_query.handler:
        class: Netgen\Layouts\Ez\TagsQuery\Handler\TagsQueryHandler
        arguments:
            - "@ezpublish.api.service.location"
            - "@netgen_layouts.ezplatform.search_service"
            - "@netgen_layouts.ezplatform.content_provider"
            - "@ezpublish.config.resolver"
            - "@request_stack"
        tags:
            - { name: netgen_layouts.query_type_handler, type: ezcontent_tags }
