services:
    netgen_layouts.tags_query.handler:
        class: Netgen\Layouts\TagsQuery\Handler\TagsQueryHandler
        # Needs to be lazy since we're injecting "languages" dynamic param
        lazy: true
        arguments:
            - "@ezpublish.api.service.location"
            - "@netgen_layouts.ezplatform.search_service"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "@netgen_layouts.ezplatform.content_provider"
            - "@request_stack"
        calls:
            - [setLanguages, ["$languages$"]]
        tags:
            - { name: netgen_layouts.query_type_handler, type: ezcontent_tags }
